const { DISCORD_TOKEN, GOOGLE_APPLICATION_CREDENTIALS, OPENAI_API_KEY, MONGODB_URI, REDIS_URL, LOG_LEVEL, LOG_FORMAT } = process.env;

module.exports = {
  DISCORD_TOKEN,
  GOOGLE_APPLICATION_CREDENTIALS,
  OPENAI_API_KEY,
  MONGODB_URI,
  REDIS_URL,
  LOG_LEVEL,
  LOG_FORMAT,
};